# event
# Job
# Step
# Action
name: 'Install dependencies'
description: 'install npm dependencies'
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm install
      shell: bash